version: '3.8'
services:
  mongo:
    image: 'mongo'
    network_mode: host
    container_name: mongo

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on: 
      - redis

  notification-service:
    container_name: notification-service
    build: 
      context: ./
    env_file: 
      - .dev.env
    network_mode: host
    depends_on: 
      - redis
      - mongo
