version: '3.8'
services:
  mongo:
    image: 'mongo'
    network_mode: host
    container_name: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_URL: amqp://admin:admin@localhost:5672
