###
POST http://localhost:3003/notifications
content-type: application/json

{   
    "type": "single",
    "body": "second notification",
    "title": "notification title",
    "delivery_method": "push",
    "consumers": ["sfdfas", "dsfsdf"]
}