@startuml general-flow
hide footbox
skinparam maxMessageSize 150



participant "Backend API" as bs

box "notification service" #LightCyan
participant "Notification API" as ns
database "DB" as ndb
queue "redis cache" as q
participant "SMS/Push API" as papi
end box

actor user

bs -> ns : add notification request
ns -> ndb: store notification
ns -> bs: accepted (202)
alt periodic redis-based queue
  ns -> ns: gets notifcations from DB
  ns -> q: add each notification in a job and store it in a queue
  ns -> papi: process each job and send the notification based on its type to a provider
end
papi -> user: send the notification to one/many user(s)
@enduml